### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sebastianlobo** [JBallin/beer-pong#5]
Was wondering if you could please add a license. Thanks!

**Comment by JBallin** [comment]
@isMeCoder thanks for checking out the app! Added an MIT License. Were you interested in using the app somehow?

**Comment by sebastianlobo** [comment]
Thank you! Not at the moment, I'm learning AR Kit, and unsatisfied with the tutorials online I found this project via Google and wanted to play with it to learn functionality.

**Comment by JBallin** [comment]
Gotcha, good luck!
FWIW, I learned the Swift basics on [Treehouse](https://teamtreehouse.com/tracks/beginning-swift) and got a lot of inspiration for this project from [Udacity](https://www.udacity.com/course/learn-arkit-using-swift--ud116).

**Comment by sebastianlobo** [comment]
Thank you! What did you use to create the 3D assets like the cups? Did you create them in XCode or an external tool?

**Comment by JBallin** [comment]
I built the cups and table manually in Xcode, and built the balls programmatically.
